## decimal zip

In [122]:
## decimal zip
def solution(A, B):
        
    a = str(A)
    b = str(B)
    output = ""
    if len(a)<=len(b):
        length=len(a)
        rest=b[length:]
    else:
        length=len(b)
        rest=a[length:]
        
    for i in range(0,length):
        if (a[i]):
            output = output + a[i];
        if (b[i]):
            output = output + b[i];
    output+=rest
    output=int(output)
    return output

### Test

In [123]:
solution(123,456)

142536

In [120]:
solution(12323,7986381311)

172938263381311

In [121]:
solution(123908766,86537)

18263593078766

## maximum time

In [125]:
## maximum time
import itertools
from datetime import datetime
def solution(a, b, c, d):
    for t in itertools.permutations([a, b, c, d]):
        clock = ''.join(map(str, t))
        try:
            new_time = datetime.strptime(clock,'%H%M')

            if 'max_time' not in locals():
                max_time = new_time
                maxclock=clock
            elif new_time > max_time:
                max_time = new_time
                maxclock=clock
        except ValueError:
            pass

    if 'max_time' not in locals():
        return "NOT POSSIBLE"
    else:
        return maxclock[0:2] + ":" + maxclock[2:4]

### Test

In [126]:
solution(1,7,9,2)

'19:27'

In [127]:
solution(2,4,0,0)

'20:40'

In [128]:
solution(1,9,9,7)

'NOT POSSIBLE'

In [129]:
solution(3,0,7,0)

'07:30'

## Ticket

In [130]:
## Ticket
def solution(A):
    A=sorted(A)
    single=0
    seven=0
    i=0
    while i<len(A):
        index=A[i]+6
        days=len(filter(lambda x: x>=A[i] and x<=index, A))
        if days>3:
            seven+=1
        elif days>0:
            single+=days
        else:
            single+=1
        try:
            i = A.index(filter(lambda x: x>index, A)[0])
        except:
            break
    payment = (single * 2) + (seven * 7)
    if (payment > 25):
        payment = 25
    return payment

### Test

In [134]:
import numpy as np
A=np.unique(np.random.randint(1,30,2))
print A
solution(A)

[ 2 22]


4

In [135]:
A=np.unique(np.random.randint(1,30,12))
print A
solution(A)

[ 5 12 17 19 20 23 24 26 27]


17

In [137]:
A=np.unique(np.random.randint(1,30,22))
print A
solution(A)

[ 3  4  5  7  9 10 11 12 13 17 18 23 24 25 26 28 29]


25

In [138]:
A=np.unique(np.random.randint(1,30,15))
print A
solution(A)

[ 2  5  8 11 12 14 15 16 17 18 19 22 23 28]


22